title: 11 O'Clock Number
description: edmonton's improvised musical
show_downloads: false
git_branch: gh-pages
comments: true
logo_url: http://www.grindstonetheatre.ca/wp-content/uploads/2016/02/11-oclock-number-banner.jpg
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: true
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
